### ISSUE TITLE
"No module named lib.utils" error

### ISSUE THREAD

**Issue by bets90** [eon01/DoMonit#1]
After following the installation guide running the `python examples.py` results in the following error.

Traceback (most recent call last):
  File "examples.py", line 4, in <module>
    from api.containers import Containers
  File "................/domonit/DoMonit/api/containers.py", line 5, in <module>
    from lib.utils import Utils
ImportError: No module named lib.utils

**Comment by eon01** [comment]
Hello @bets90 , the lib folder was untracked during my commit because it was ignored in .gitignore file. 
Thank you for opening the issue, I just fixed it !
